var array = new Array (10);
document.write(array[2] + "<br>");
array = new Array(10,11);
document.write(array + "<br>");
var array1 = ["Anna", 234, 'ling'];
document.write(array1 + "<br>");
array[4] = "Yes";
document.write(array + "<br>");
var anArray = [1,2,3,4];
anArray[4] = 4;
document.write(anArray + "<br>");
anArray[6] = 10;
document.write(anArray + "<br>");
anArray[3] = "Anna";
document.write(anArray + "<br>");
anArray.pop();
document.write(anArray + "<br>");
anArray.shift();
document.write(anArray + "<br>");
anArray.splice(1,2, "Amin", "Facu");
document.write(anArray + "<br>");
var anArray1 = [1,2,3,4];
var n = anArray1.pop();
document.write(anArray1 + "<br>");
var m = anArray1.unshift(5,6);
document.write(anArray1 + "<br>");
var p = anArray1.shift();
document.write(anArray1 + "<br>");
var r = anArray1.push(1,2);
document.write(anArray1 + "<br>");
anArray2 = [1,2,3,4];
var s = anArray2.concat(anArray2);
document.write(anArray2 + "<br>");
anArray2.splice(1,1);
document.write(anArray2 + "<br>");
anArray2.splice(1,0,5,7);
document.write(anArray2 + "<br>");
anArray2.splice(2,2,6,8);
document.write(anArray2 + "<br>");
